[package]
name = "tsp-solver"
version = "0.1.0"
authors = ["Kasper Ziemianek <kasper.ziemianek@gmail.com>"]
edition = "2018"

[lib]
name = "tspsolver"
path = "src/lib.rs"


[dependencies]
metaheuristics = "0.0.6"
rand = "0.7.3"
time = {version = "0.1.30", default-features= false}